# TODO's


# TODO Fix the issue where the issue where the sentence is left un-generated by the token limit
# TODO Make a connection to a DB that stores user data, somehow keeps it secure (read up on this)
# TODO Optimize storage data speeds
# TODO Make a work around for storing JSON's
# TODO Auth

# TODO Optimize the path-way for using the model, and initializing it
# TODO Update the pathway, so it's very linear, but also make sure the code is build-upon-able
# TODO try memory management, if time permits
# TODO Make CuBlas work, find the code that used to make it work
# TODO Make sure it works only once per person
# TODO Make it so that multiple people can use it at the same time using only one branch of the AI model

# TODO UX
# TODO Make it so that it's the best model that can be used
# TODO Find a good prompt for staying on context

# TODO Indexing
# TODO Use a good model for the sentence transformers, space and quality wise
# TODO Make sure the indexing works as intended with a 100% hit ratio

# TODO Use cases
# TODO Talk to Cons
# TODO Talk to only bot, can do some basic QnA
# TODO Summarize ( @Andyyy )
# TODO Talk to Summary
